require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/toys", type: :request do
  
  # Toy. As you add validations to Toy, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Toy.create! valid_attributes
      get toys_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      toy = Toy.create! valid_attributes
      get toy_url(toy)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_toy_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      toy = Toy.create! valid_attributes
      get edit_toy_url(toy)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Toy" do
        expect {
          post toys_url, params: { toy: valid_attributes }
        }.to change(Toy, :count).by(1)
      end

      it "redirects to the created toy" do
        post toys_url, params: { toy: valid_attributes }
        expect(response).to redirect_to(toy_url(Toy.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Toy" do
        expect {
          post toys_url, params: { toy: invalid_attributes }
        }.to change(Toy, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post toys_url, params: { toy: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested toy" do
        toy = Toy.create! valid_attributes
        patch toy_url(toy), params: { toy: new_attributes }
        toy.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the toy" do
        toy = Toy.create! valid_attributes
        patch toy_url(toy), params: { toy: new_attributes }
        toy.reload
        expect(response).to redirect_to(toy_url(toy))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        toy = Toy.create! valid_attributes
        patch toy_url(toy), params: { toy: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested toy" do
      toy = Toy.create! valid_attributes
      expect {
        delete toy_url(toy)
      }.to change(Toy, :count).by(-1)
    end

    it "redirects to the toys list" do
      toy = Toy.create! valid_attributes
      delete toy_url(toy)
      expect(response).to redirect_to(toys_url)
    end
  end
end
