on:
  push:
    branches:
      - main
      - rake-cucumber
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gunpla_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.84.0
        with:
          bundler-cache: true
      - name: Rake Test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: gunpla_test
          RAILS_ENV: test
        run: |
          bin/rails db:prepare
          echo "===  START Seed ==="
          bin/rails db:seed --trace
          echo "===  END Seed ==="
          bundle exec rake cucumber
